services:
  uwsgi:
    build: ./app
    container_name: uwsgi
    volumes:
      - ./app:/var/www
    ports:
      - "3031:3031"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uwsgi
    restart: always
